In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("caltech.csv")

df.head()

,_id,userInputs,sessionID,stationID,spaceID,siteID,clusterID,connectionTime,disconnectTime,kWhDelivered,doneChargingTime,timezone,userID
0,5bc90cb9f9af8b0d7fe77cd2,NaN,2_39_78_362_2018-04-25 11:08:04.400812,2-39-78-362,CA-496,2,39,2018-04-25 04:08:04-07:00,2018-04-25 06:20:10-07:00,7.932,2018-04-25 06:21:10-07:00,America/Los_Angeles,NaN
1,5bc90cb9f9af8b0d7fe77cd3,NaN,2_39_95_27_2018-04-25 13:45:09.617470,2-39-95-27,CA-319,2,39,2018-04-25 06:45:10-07:00,2018-04-25 17:56:16-07:00,10.013,2018-04-25 09:44:15-07:00,America/Los_Angeles,NaN
2,5bc90cb9f9af8b0d7fe77cd4,NaN,2_39_79_380_2018-04-25 13:45:49.962001,2-39-79-380,CA-489,2,39,2018-04-25 06:45:50-07:00,2018-04-25 16:04:45-07:00,5.257,2018-04-25 07:51:44-07:00,America/Los_Angeles,NaN
3,5bc90cb9f9af8b0d7fe77cd5,NaN,2_39_79_379_2018-04-25 14:37:06.460772,2-39-79-379,CA-327,2,39,2018-04-25 07:37:06-07:00,2018-04-25 16:55:34-07:00,5.177,2018-04-25 09:05:22-07:00,America/Los_Angeles,NaN
4,5bc90cb9f9af8b0d7fe77cd6,NaN,2_39_79_381_2018-04-25 14:40:33.638896,2-39-79-381,CA-490,2,39,2018-04-25 07:40:34-07:00,2018-04-25 16:03:12-07:00,10.119,2018-04-25 10:40:30-07:00,America/Los_Angeles,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               15000 non-null  str
 1   userInputs        2233 non-null   str
 2   sessionID         15000 non-null  str
 3   stationID         15000 non-null  str
 4   spaceID           15000 non-null  str
 5   siteID            15000 non-null  int64
 6   clusterID         15000 non-null  int64
 7   connectionTime    15000 non-null  str
 8   disconnectTime    15000 non-null  str
 9   kWhDelivered      15000 non-null  float64
 10  doneChargingTime  14992 non-null  str
 11  timezone          15000 non-null  str
 12  userID            2233 non-null   float64
dtypes: float64(2), int64(2), str(9)
memory usage: 1.5 MB

In [4]:
df.isnull().sum()

_id                     0
userInputs          12767
sessionID               0
stationID               0
spaceID                 0
siteID                  0
clusterID               0
connectionTime          0
disconnectTime          0
kWhDelivered            0
doneChargingTime        8
timezone                0
userID              12767
dtype: int64

In [5]:
df['connectionTime'] = pd.to_datetime(df['connectionTime'])

df['disconnectTime'] = pd.to_datetime(df['disconnectTime'])

df['doneChargingTime'] = pd.to_datetime(df['doneChargingTime'])

ValueError: Mixed timezones detected. Pass utc=True in to_datetime or tz='UTC' in DatetimeIndex to convert to a common timezone.

In [6]:
df['connectionTime'].head()

0    2018-04-25 04:08:04-07:00
1    2018-04-25 06:45:10-07:00
2    2018-04-25 06:45:50-07:00
3    2018-04-25 07:37:06-07:00
4    2018-04-25 07:40:34-07:00
Name: connectionTime, dtype: str

In [7]:
df['connectionTime'] = pd.to_datetime(
    df['connectionTime'],
    errors='coerce'
)

df['disconnectTime'] = pd.to_datetime(
    df['disconnectTime'],
    errors='coerce'
)

df['doneChargingTime'] = pd.to_datetime(
    df['doneChargingTime'],
    errors='coerce'
)

ValueError: Mixed timezones detected. Pass utc=True in to_datetime or tz='UTC' in DatetimeIndex to convert to a common timezone.

In [8]:
df['connectionTime'] = pd.to_datetime(
    df['connectionTime'],
    utc=True
)

df['disconnectTime'] = pd.to_datetime(
    df['disconnectTime'],
    utc=True
)

df['doneChargingTime'] = pd.to_datetime(
    df['doneChargingTime'],
    utc=True
)

In [9]:
df[['connectionTime','disconnectTime','doneChargingTime']].head()

,connectionTime,disconnectTime,doneChargingTime
0,2018-04-25 11:08:04+00:00,2018-04-25 13:20:10+00:00,2018-04-25 13:21:10+00:00
1,2018-04-25 13:45:10+00:00,2018-04-26 00:56:16+00:00,2018-04-25 16:44:15+00:00
2,2018-04-25 13:45:50+00:00,2018-04-25 23:04:45+00:00,2018-04-25 14:51:44+00:00
3,2018-04-25 14:37:06+00:00,2018-04-25 23:55:34+00:00,2018-04-25 16:05:22+00:00
4,2018-04-25 14:40:34+00:00,2018-04-25 23:03:12+00:00,2018-04-25 17:40:30+00:00

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   _id               15000 non-null  str
 1   userInputs        2233 non-null   str
 2   sessionID         15000 non-null  str
 3   stationID         15000 non-null  str
 4   spaceID           15000 non-null  str
 5   siteID            15000 non-null  int64
 6   clusterID         15000 non-null  int64
 7   connectionTime    15000 non-null  datetime64[us, UTC]
 8   disconnectTime    15000 non-null  datetime64[us, UTC]
 9   kWhDelivered      15000 non-null  float64
 10  doneChargingTime  14992 non-null  datetime64[us, UTC]
 11  timezone          15000 non-null  str
 12  userID            2233 non-null   float64
dtypes: datetime64[us, UTC](3), float64(2), int64(2), str(6)
memory usage: 1.5 MB

In [11]:
df['session_duration_hours'] = (
    df['disconnectTime'] - df['connectionTime']
).dt.total_seconds() / 3600

df['charging_duration_hours'] = (
    df['doneChargingTime'] - df['connectionTime']
).dt.total_seconds() / 3600

In [12]:
df[['session_duration_hours',
    'charging_duration_hours']].describe()

       session_duration_hours  charging_duration_hours
count            15000.000000             14992.000000
mean                 5.924281                 3.236711
std                  6.459733                 3.185358
min                  0.087500                -0.689444
25%                  2.025208                 1.271875
50%                  4.765000                 2.241667
75%                  8.729722                 4.244722
max                245.269167               104.428333

In [13]:
negative_charging = df[df['charging_duration_hours'] < 0]

print(len(negative_charging))

18

In [14]:
df = df[df['charging_duration_hours'] >= 0]

In [15]:
df['utilization_rate'] = (
    df['charging_duration_hours'] /
    df['session_duration_hours']
)

In [16]:
df['utilization_rate'].describe()

count    14974.000000
mean         0.692711
std          0.325231
min          0.000000
25%          0.389336
50%          0.816569
75%          0.998649
max          1.159030
Name: utilization_rate, dtype: float64

In [17]:
print(df['connectionTime'].min())
print(df['connectionTime'].max())

2018-04-25 11:08:04+00:00
2018-12-16 07:33:17+00:00

In [18]:
df.to_csv(
    "processed_caltech.csv",
    index=False
)